### ISSUE TITLE
Feature Request: Danger Zone for deletion UI

### ISSUE THREAD

**Issue by ghost** [Beee4life/b3-onboarding#26]
I'd like to see the inclusion of an additional safety feature in the account deletion user interface (UI). This safety feature would be in the form of a "danger zone drawer," which can be accessed by clicking on a button. When the button is clicked, the danger zone drawer would reveal the account deletion UI.

The purpose of this feature would be to provide an added layer of protection against the accidental deletion of user accounts. By placing the account deletion UI behind an extra button, users would be less likely to accidentally delete their accounts, as they would need to consciously click through an additional step to access it.

The term "danger zone" here refers to the area of the UI that contains potentially risky actions, such as deleting an account. By creating a separate drawer for this area, it becomes more difficult to accidentally trigger these actions.

Overall, the addition of a danger zone drawer to the account deletion UI could be a useful safety feature that allows users to delete their accounts only if they are absolutely certain.

**Comment by Beee4life** [comment]
Hi Lewis, thanks for the comment. I wasn't aware some other people were already using it. i thought it was mostly people I know, around me... 

I understand your comment and I do feel there's some merit to it... I will look into adding an extra layer/confirmation for deletion.

**Comment by ghost** [comment]
Awesome! I love the plugin btw. Truth be told I stumbled across it while searching the web for a robust & lightweight onboarding plugin for WP. There are plenty of solutions out there, but I'm really attracted to how clean and simple your solution is. 

If you're open to suggestions I have a couple more that I can provide in new issues if you'd like.

**Comment by Beee4life** [comment]
thank for the compliment... i have planned to upload it to the WP library later this year as well.

feel free to suggest, no guarantees I'll implement them though.

**Comment by ghost** [comment]
> feel free to suggest, no guarantees I'll implement them though.

-I totally, understand. 👌🏻.

I'll open some new topics sometime later today or tomorrow with some suggested improvements.

Thanks again for taking the time to put this plugin together, it's about time WP had something lightweight and usable for the onboarding process.
